### ISSUE TITLE
bitbucket configuration

### ISSUE THREAD

**Issue by mkardakov** [isaaceindhoven/composer-velocita#4]
Hi! I would like to try this tool for private bitbucket repository.
Could you please explain what is right name of the mirror_{name}_url in this case? I have tried to use our repository domain but it seems does not work. I see no file cache in velocita cache directory in this case
I have tried the following env:
MIRROR_BITBUCKET_URL: https://bitbucket.my.company/rest/api/1.0/repos
and
MIRROR_BITBUCKET_URL: https://bitbucket.my.company

2. Is it possible to debug this tool? to understand if something is cached by proxy or not

**Comment by gmta** [comment]
> Could you please explain what is right name of the mirror_{name}_url in this case?

Exactly the same URL you would otherwise use for the `repositories` in `composer.json`. See https://getcomposer.org/doc/05-repositories.md#composer

> I have tried to use our repository domain but it seems does not work. I see no file cache in velocita cache directory in this case

If you mean the Velocita server, you should indeed see the cache directory filling up with files if everything is working correctly. Did you actually install and enable the Velocita Composer plugin as well on the client side?

> Is it possible to debug this tool?

You can add verbosity to `composer` like this:
```
composer install -vvv
```

The Velocita plugin will report if it rewrites URLs and Composer will report the URL it actually downloads if a package or its metadata is not yet in the local Composer cache. If you do not see URL rewrites or if Composer does not show a download URL that points to your Velocita server instance, something is not working correctly.

**Comment by mkardakov** [comment]
> If you mean the Velocita server, you should indeed see the cache directory filling up with files if everything is working correctly. Did you actually install and enable the Velocita Composer plugin as well on the client side?

Yes, I installed Velocita server as docker image. I see the cache folder is populated for packagist and github mirrors. And no cache for bitbucket. The repositories located at bitbucket are private and we are using ssh authentication (type = vcs) to download them. Can it be the reason for the problem?
I mean should it be MIRROR_BITBUCKET_URL: ssh://stash.dev.mycompany.dev instead of https://stash.dev.mycompany.dev ?

**Comment by gmta** [comment]
Hi @mkardakov,

SSH authentication is not something Velocita supports yet - you point directly to a Git repository and use SSH keys on a personal level for access. However, a Git repository is not a Composer repository - it's just that Composer has support for it. Sharing SSH keys with multiple developers through a cache lends itself to all kinds of data exposures you might not want.

Velocita's goal is to cache Composer repositories, which usually are very stable in the packages and metadata that is published. You could create a private repository (for example, using [Satis](https://github.com/composer/satis)) and then point Velocita to that private repository. But if you have that private repository up and running, adding a cache to that will offer very few benefits.

**Comment by mkardakov** [comment]
@GMTA ok, thank you! Closing the issue
